<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="DestructuramaFSharp.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="Serilog" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference PrivateAssets="All" Include="MinVer" />
  </ItemGroup>

  <ItemGroup>
    <None Pack="true" PackagePath="/" Visible="false" Include="../../assets/icon.png"  />
    <None Pack="true" PackagePath="/" Visible="false" Include="../../README.md" />
  </ItemGroup>

</Project>
