<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Tests.fs" />
  </ItemGroup>

  <ItemGroup Label="Project under test">
    <ProjectReference Include="../Destructurama.FSharp/Destructurama.FSharp.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference PrivateAssets="all" Include="coverlet.collector" />
    <PackageReference PrivateAssets="all" Include="Microsoft.NET.Test.Sdk" />
    <PackageReference PrivateAssets="all" Include="xunit.runner.visualstudio" />
  </ItemGroup>

</Project>
