version: '{build}'
skip_tags: true
image:
  - Visual Studio 2019
  - Ubuntu1804
configuration: Release
test: off
install:
  - ps: ./Setup.ps1
build_script:
  - ps: ./Build.ps1
for:
-
  matrix:
    only:
      - image: Ubuntu1804
  install:
  - sh setup.sh
  build_script:
  - sh build.sh
artifacts:
- path: artifacts/Destructurama.FSharp.*.nupkg
- path: artifacts/Destructurama.FSharp.*.snupkg
deploy:
- provider: NuGet
  api_key:
    secure: 8pYzSkAQQO5cO0w8GuNXpEnve1TWud2ilZRXgbuY5hcmHVqfpXaDHolN5YTRyyYG
  skip_symbols: true
  on:
    branch: /^(master|dev)$/

