<Project>

  <PropertyGroup>
    <LangVersion>10.0</LangVersion>
    <OutputType>library</OutputType>
    <IsPackable>false</IsPackable>
    <IsPublishable>false</IsPublishable>
    <DisableImplicitFSharpCoreReference>true</DisableImplicitFSharpCoreReference>
    <DisableImplicitSystemValueTupleReference>true</DisableImplicitSystemValueTupleReference>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <EmbedAllSources>true</EmbedAllSources>
    <DebugType>embedded</DebugType>
    <NuGetAuditMode>all</NuGetAuditMode>
  </PropertyGroup>

  <PropertyGroup>
    <Description>
      <![CDATA[
        An F# package providing custom and advanced destructuring for Serilog.
      ]]>
    </Description>
    <Authors>Destructurama Contributors, Serilog Contributors</Authors>
    <CurrentYear>$([System.DateTime]::Now.ToString(yyyy))</CurrentYear>
    <Copyright>Copyright © Serilog Contributors 2019-$(CurrentYear)</Copyright>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageTags>serilog;fsharp</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <PackageIcon>icon.png</PackageIcon>
  </PropertyGroup>
  
  <PropertyGroup>

    <!-- https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables -->
    <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">True</ContinuousIntegrationBuild>
  
    <Nullable>enable</Nullable>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>../../assets/Destructurama.snk</AssemblyOriginatorKeyFile>
    <!--https://github.com/dotnet/BenchmarkDotNet/issues/836-->
    <AssemblyOriginatorKeyFile Condition="EXISTS('../../../../../../assets/Destructurama.snk')">../../../../../../assets/Destructurama.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

</Project>
